config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'posts#index'

  resources :posts do
    resources :tags#, only: [:destroy]
    resources :file_uploads, only: [:new, :create, :destroy]
  end

  resources :users

  get   '/search'    => 'posts#search', :as => 'search_page'
  get   '/rate'    => 'posts#rate', :as => 'rate_page'

  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # custom routes
  delete '/posts/:post_id/tags/:id', to: 'tag#destroy', as: 'destroy_post_tag_path'
  #get '/posts/:id', to: 'patients#show', as: 'patient'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :full_name, presence: true, length: {maximum: 50}
  validates :password, presence: true, length: {minimum: 6}
  VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false}
  before_save { self.email = email.downcase }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:new, :create]
  before_action :correct_user?, except: [:new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        sign_in(@user)
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    sign_out
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:full_name, :email, :gender, :birth_date, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> evitou que este usuário fosse gravado:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Nome:
    <%= form.text_field :full_name %>
  </div>

  <div class="field">
    E-mail:
    <%= form.text_field :email %>
  </div>

  <div class="field">
    Senha:
    <%= form.password_field  :password %>
  </div>

  <div class="field">
    Confirmação da senha:
    <%= form.password_field  :password_confirmation %>
  </div>

  <div class="field">
    Sexo:
    <%= form.select :gender, ["Masculino", "Feminino", "Outros"] %>
  </div>

  <div class="field">
    Data de nascimento:
    <%= form.date_select :birth_date, order: [:day, :month, :year], start_year: 1920 %>
  </div>

  <div class="actions">
    <%= form.submit "Gravar" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editar Usuário</h1>

<%= render 'form', user: @user %>

<%= link_to 'Mostrar', @user %> |
<%= link_to "Apagar", @user, method: :delete%> |
<%= link_to 'Voltar', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Email</th>
      <th>Gender</th>
      <th>Birth date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.full_name %></td>
        <td><%= user.email %></td>
        <td><%= user.gender %></td>
        <td><%= user.birth_date %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Novo Usuário</h1>

<%= render 'form', user: @user %>

<%= link_to 'Voltar', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>
    Perfil de <%= @user.full_name %>
  </strong>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @user.gender %>
</p>

<p>
  <strong>Data de nascimento:</strong>
  <%= @user.birth_date.strftime("%d/%m/%Y") %>
</p>

<% if current_user == @user %>
  <%= link_to 'Editar', edit_user_path(@user) %> |
  <%= link_to "Apagar", @user, method: :delete%> |
<%end%>

<%= link_to 'Voltar', posts_path %>