config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'posts#index'

  resources :posts do
    resources :tags#, only: [:destroy]
    resources :file_uploads, only: [:new, :create, :destroy]
  end

  resources :users

  get   '/search'    => 'posts#search', :as => 'search_page'
  get   '/rate'    => 'posts#rate', :as => 'rate_page'

  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # custom routes
  delete '/posts/:post_id/tags/:id', to: 'tag#destroy', as: 'destroy_post_tag_path'
  #get '/posts/:id', to: 'patients#show', as: 'patient'
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_and_belongs_to_many :posts

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]
  before_action :authorize
  before_action :correct_user?

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  # GET /posts/1/tags/1/new
  def new
    @post = Post.find(params[:post_id])

    # check if it tries to add the tag
    @add_tag = true

    # check for empty tag text
    if (params[:tag_text].blank?)
      @add_tag = false
    end

    # check for existing relationship
    if (@add_tag)
      @post.tags.each do |tag|
        if tag.tag_text == params[:tag_text]
          @add_tag = false
        end
      end
    end

    # check for existing tags
    if (@add_tag)
      @query_tags = Tag.where("tag_text = ?", params[:tag_text])

      # if tag does not exist on database, create it
      if @query_tags.size == 0
        @tag = Tag.new
        @tag.tag_text = params[:tag_text]
      else
        @tag = @query_tags.first
      end

      @post.tags << @tag
      @post.save
    end

    respond_to do |format|
      format.html { redirect_to @post }
      format.json { head :no_content }
      format.js { render :layout => false }
    end
  end

  # GET /tags/1/edit
  # GET /posts/1/tags/1/edit
  def edit

  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @post = Post.find(params[:post_id])

    # remove tag from post
    @post.tags = @post.tags.reject {|item| (item.id == params[:id].to_i)}

    @post.save

    respond_to do |format|
      format.html { redirect_to @post }
      format.json { head :no_content }
      format.js { render :layout => false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:tag_text)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% tag.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tag_text %>
    <%= form.text_field :tag_text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<p>
  <strong>Tag:</strong>
  <%= tag.tag_text %>
</p>

<p>
  <%= link_to 'Destroy Tag', tag,
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/tags/destroy.js.erb
$('.tags_target').bind('ajax:success', function() {
   $(this).closest('div').fadeOut();
});

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>Tag text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.tag_text %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/new.js.erb
var added = <%= @add_tag %>;
var post_id = <%= @post ? (@post.id) : (0) %>;
var tag_id = <%= @tag ? (@tag.id) : (0) %>;

if (added) {
  var tag = '<div>' + $("#tag_text").val();
  tag += ' <a update="tags_target" class="tags_target" data-remote="true" rel="nofollow" ';
  tag += 'data-method="delete" href="/posts/'+post_id+'/tags/'+tag_id+'">(x)</a></div>';

  $('.tag_list').append(tag);
}

$('#tag_text').val("");

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tag text:</strong>
  <%= @tag.tag_text %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>