config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'posts#index'

  resources :posts do
    resources :tags#, only: [:destroy]
    resources :file_uploads, only: [:new, :create, :destroy]
  end

  resources :users

  get   '/search'    => 'posts#search', :as => 'search_page'
  get   '/rate'    => 'posts#rate', :as => 'rate_page'

  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # custom routes
  delete '/posts/:post_id/tags/:id', to: 'tag#destroy', as: 'destroy_post_tag_path'
  #get '/posts/:id', to: 'patients#show', as: 'patient'
end

app/models/post.rb
class Post < ApplicationRecord
  after_initialize :set_defaults

  belongs_to :user

  belongs_to :year
  belongs_to :subject
  belongs_to :topic

  has_and_belongs_to_many :tags

  has_many_attached :files

  def title
    self.year.year_text + " - " + self.subject.subject_text + " - " + self.topic.topic_text
  end

  def blank_stars
   5 - rating.to_i
  end

  def set_defaults
    if !self.rating.present?
      self.rating = "0"
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :rate]
  before_action :authorize, except: [:index, :show]
  before_action :correct_user?, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index

    if params[:search].present? # search posts
      @parameter = params[:search].downcase
      if @parameter.size >= 3
        #@posts = Post.all.where("lower(year) LIKE :search", search: "%#{@parameter}%")
        @posts = Post.joins(:year).where("lower(years.year_text) LIKE :search", search: "%#{@parameter}%")
      else
        #@posts = Post.all.order(:year)
        @posts = Post.joins(:year).order('years.year_text')
      end
    elsif params[:format].present? # filter by user
      #@posts = Post.where(user_id: current_user.id).order(:year)
      @posts = Post.joins(:year).where(user_id: current_user.id).order('years.year_text')
    else # show all posts
      #@posts = Post.joins('LEFT OUTER JOIN years ON posts.year_id = years.id').order('years.year_text')
      @posts = Post.joins(:year).order('years.year_text')
    end
  end

  # GET /search
  def search
    if !params[:search].blank?
      @parameter = params[:search].downcase
      #@posts = Post.all.where("lower(year) LIKE :search", search: "%#{@parameter}%")
      @posts = Post.joins(:year).where("lower(years.year_text) LIKE :search", search: "%#{@parameter}%")
    else
      #@posts = Post.all
      @posts = Post.joins(:year).order('years.year_text')
    end

    redirect_to posts_url
  end

  # GET /rate
  def rate
    if !params[:rate_id].blank?
      @post.rating = params[:rate_id].to_i
      @post.save
    end

    redirect_to @post
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    # get list of tags for search
    @tags = Tag.pluck(:tag_text).sort

    # check if the post can be edited
    @can_edit = current_user.present? && @post.user_id == current_user.id

    # increment views
    if !@post.views.present?
      @post.views = 1
    else
      @post.views = @post.views + 1
    end

    @post.save
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.year = Year.new
    @post.subject = Subject.new
    @post.topic = Topic.new

    @years = Year.pluck(:year_text).sort
    @subjects = Subject.pluck(:subject_text).sort
    @topics = Topic.pluck(:topic_text).sort
  end

  # GET /posts/1/edit
  def edit
    # get list of data for search on autocomplete
    @years = Year.pluck(:year_text).sort
    @subjects = Subject.pluck(:subject_text).sort
    @topics = Topic.pluck(:topic_text).sort
  end

  # POST /posts
  # POST /posts.json
  def create
    @year_id = getYearFromText(params[:year_text])
    @subject_id = getSubjectFromText(params[:subject_text])
    @topic_id = getTopicFromText(params[:topic_text])

    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.year_id = @year_id
    @post.subject_id = @subject_id
    @post.topic_id = @topic_id

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: 'Resumo criado com sucesso.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      @year_id = getYearFromText(params[:year_text])
      @subject_id = getSubjectFromText(params[:subject_text])
      @topic_id = getTopicFromText(params[:topic_text])

      @post.year_id = @year_id
      @post.subject_id = @subject_id
      @post.topic_id = @topic_id

      if @post.update(post_params)
        format.html { redirect_to posts_url, notice: 'Resumo atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Resumo excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:year, :subject, :topic, :published, :favorite, :user_id)
    end

    def getYearFromText(text)
      @year = Year.find_by(year_text: text)
      if !@year.present?
        @year = Year.new
        @year.year_text = text
        @year.save
      end
      return @year.id
    end

    def getSubjectFromText(text)
      @subject = Subject.find_by(subject_text: text)
      if !@subject.present?
        @subject = Subject.new
        @subject.subject_text = text
        @subject.save
      end
      return @subject.id
    end

    def getTopicFromText(text)
      @topic = Topic.find_by(topic_text: text)
      if !@topic.present?
        @topic = Topic.new
        @topic.topic_text = text
        @topic.save
      end
      return @topic.id
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> impediram a gravação deste resumo:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div id= "search-data-year" name="search-data-year" class="form-search search-data autocomplete"
      style="border-top: 1px solid #eee;border-bottom:1px solid #eee;background:#fafafa;margin:30px 0;padding:20px 10px;text-align:center"
      data-skills="<%= @years.to_json %>">
      Ano: <%= text_field_tag :year_text, @post.year.year_text,
            autocomplete: :off, class: "form-control search-input", sytle: "width:100%;max-width:600px;outline:0"%>
    </div>
  </div>

  <div class="field">
    <div id= "search-data-subject" name="search-data-subject" class="form-search search-data autocomplete"
      style="border-top: 1px solid #eee;border-bottom:1px solid #eee;background:#fafafa;margin:30px 0;padding:20px 10px;text-align:center"
      data-skills="<%= @subjects.to_json %>">
      Matéria: <%= text_field_tag :subject_text, @post.subject.subject_text,
            autocomplete: :off, class: "form-control search-input", sytle: "width:100%;max-width:600px;outline:0"%>
    </div>
  </div>

  <div class="field">
    <div id= "search-data-topic" name="search-data-topic" class="form-search search-data autocomplete"
      style="border-top: 1px solid #eee;border-bottom:1px solid #eee;background:#fafafa;margin:30px 0;padding:20px 10px;text-align:center"
      data-skills="<%= @topics.to_json %>">
      Assunto: <%= text_field_tag :topic_text, @post.topic.topic_text,
            autocomplete: :off, class: "form-control search-input", sytle: "width:100%;max-width:600px;outline:0"%>
    </div>
  </div>

  <div class="field">
    Publicar? <%= form.check_box :published %>
  </div>

  <div class="field">
    Favorito? <%= form.check_box :favorite %>
  </div>

  <!-- List tags -->
  <% if @post.id %>
    <p>
     Tags:
     <% if @post.tags.empty? %>
        Nenhuma tag
     <% end %>

     <% @post.tags.each do |tag| %>
       <%= tag.tag_text %>
     <% end %>
    </p>
  <% end %>

  <!-- List files -->
  <% if @post.id %>
    Anexos:
    <% if @post.files.empty? %>
       Nenhum anexo
    <% end %>

    <ul>
     <% @post.files.each do |file| %>
        <li>
          <%= link_to file.filename, url_for(file), target: :_blank%>
        </li>
     <% end %>
    </ul>
  <% end %>

  <!-- Rating -->
  <% if @post.id %>
    Rating:
    <%= link_to '', rate_page_url(id: @post.id, rate_id: 0), :class => "glyphicon glyphicon-remove-circle link_no_underline" %>
    <% @post.rating.to_i.times do |i|  %>
     <%= link_to '', rate_page_url(id: @post.id, rate_id: i+1), :class => "glyphicon glyphicon-star link_no_underline" %>
    <% end %>
    <% @post.blank_stars.times do |i| %>
     <%= link_to '', rate_page_url(id: @post.id, rate_id: @post.rating+i+1), :class => "glyphicon glyphicon-star-empty link_no_underline" %>
    <% end %>
  <% end %>

  <p/>

  <div class="actions">
    <%= form.submit "Gravar resumo" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Exibir', @post %> |
<%= link_to 'Voltar', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Resumos</h1>

<table>
  <thead>
    <tr>
      <th>Ano</th>
      <th>Matéria</th>
      <th>Assunto</th>
      <th>Autor</th>
      <th>Tags</th>
      <th>Anexos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.year.year_text %></td>
        <td><%= post.subject.subject_text %></td>
        <td><%= post.topic.topic_text %></td>
        <td>
          <%= User.find(post.user_id).full_name %>
        </td>
        <td>
          <% post.tags.each do |tag| %>
            <%= tag.tag_text %>
            <br/>
          <% end %>
        </td>
        <td>
          <ul>
           <% post.files.each do |file| %>
              <li>
                <%= link_to file.filename, url_for(file), target: :_blank %>
              </li>
           <% end %>
          </ul>
        </td>
        <td><%= link_to 'Exibir', post %></td>
        <% if current_user.present? && post.user_id == current_user.id %>
          <td><%= link_to 'Editar', edit_post_path(post) %></td>
          <td><%= link_to 'Apagar', post, method: :delete, data: { confirm: 'Confirma?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Resumo', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Voltar', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ano:</strong>
  <%= @post.year.year_text %>
</p>

<p>
  <strong>Matéria:</strong>
  <%= @post.subject.subject_text %>
</p>

<p>
  <strong>Assunto:</strong>
  <%= @post.topic.topic_text %>
</p>

<p>
  <strong>Publicar?</strong>
  <%= @post.published %>
</p>

<p>
  <strong>Favorito?</strong>
  <%= @post.favorite %>
</p>

<!-- List tags -->
<p>
     <b>Tags:</b>
     <div class="tag_list">
       <% @post.tags.each do |tag| %>
        <div>
           <%= tag.tag_text %>
           <% if current_user.present? && @post.user_id == current_user.id %>
              <%= link_to "(x)", destroy_post_tag_path_url(@post, tag),
                remote: true, class: "tags_target",
                method: "delete" %>
           <% end %>
        </div>
       <% end %>
     </div>
</p>

<% if @can_edit %>
  <!-- Add new tag -->
  <%= form_tag "/posts/#{@post.id}/tags/new", {remote: true, :method => :get, :class => "form-inline"} do  %>
    <div id= "search-data-tag" name="search-data-tag" class="form-search search-data autocomplete"
      style="border-top: 1px solid #eee;border-bottom:1px solid #eee;background:#fafafa;margin:30px 0;padding:20px 10px;text-align:center"
      data-skills="<%= @tags.to_json %>">
      <b>Nova Tag:</b>
      <%= text_field_tag :tag_text, nil, autocomplete: :off, class: "form-control search-input",
        placeholder: "Buscar tags...", sytle: "width:100%;max-width:600px;outline:0" %>
      <%= submit_tag 'Adicionar Tag'  %>
    </div>
  <% end %>
<% end %>

<p/>

<!-- Attached files -->
<b>Arquivos:</b>
<ul>
  <% @post.files.each do |file| %>
    <li>
      <%= link_to file.filename, url_for(file), target: :_blank %>
      <% if @can_edit %>
        <%= link_to "(x)", post_file_upload_path(@post, file), method: :delete %>
      <% end %>
    </li>
  <% end %>
</ul>

<% if @can_edit %>
 <%= button_to 'Inserir Anexos', new_post_file_upload_path(@post), method: :get %>
<% end %>

<br/><br/>

<!-- Rating -->
<b>Rating:</b>
<% @post.rating.to_i.times do  %>
 <span class="glyphicon glyphicon-star"></span>
<% end %>
<% @post.blank_stars.times do %>
 <span class="glyphicon glyphicon-star-empty"></span>
<% end %>

<br/><br/>

<!-- Post actions -->
<% if @can_edit %>
  <%= link_to 'Editar', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Voltar', posts_path %>