config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'posts#index'

  resources :posts do
    resources :tags#, only: [:destroy]
    resources :file_uploads, only: [:new, :create, :destroy]
  end

  resources :users

  get   '/search'    => 'posts#search', :as => 'search_page'
  get   '/rate'    => 'posts#rate', :as => 'rate_page'

  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # custom routes
  delete '/posts/:post_id/tags/:id', to: 'tag#destroy', as: 'destroy_post_tag_path'
  #get '/posts/:id', to: 'patients#show', as: 'patient'
end

app/views/layouts/_header.html.erb
  <div>
      <% if logged_in? %>
        Olá <%= current_user.full_name %> |
        <%= link_to "Perfil", current_user %> |
        <%= link_to "Settings", edit_user_path(current_user) %> |
        <%= link_to "Log out", sign_out_path, method: "delete" %><br/><br/>
      <% else %>
        <%= link_to "Log in", sign_in_path %> |
      <% end %>

      <% if logged_in? %>
        <br/><br/>
        <%= link_to "Criar resumo", new_post_path(current_user) %> |
        <%= link_to "Meus resumos", posts_path(current_user) %> |
      <% end %>

      <%= link_to "Listar resumos", posts_path %>

      <br/><br/>

      <%= form_tag(posts_path, method: 'GET', class: 'navbar-form navbar-left') do %>
        <div class="input-group">
          Buscar resumos:
          <%= search_field_tag :search, params[:search], placeholder: "Buscar", class: "form-control" %>
          <%= button_tag "", :class => 'glyphicon glyphicon-search',:name => nil%>
        </div>
      <% end %>

      <br/><br/>

  </div>
<hr/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Resumos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag '_glyphicons' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>